version: '3.4'

services:
   mongodb:
    image : mongo
   redis:
    image: redis
   netcoremrd.api:
    image: ${DOCKER_REGISTRY-}netcoremrdapi
    build:
      context: .
      dockerfile: NetCoreMRD.Api/Dockerfile
